#!/bin/bash
# Install missing system libraries for Chromium/Playwright in stripped containers
# Downloads Debian bookworm packages directly and extracts to INSTALL_DIR
#
# Usage: ./install-system-libs.sh [INSTALL_DIR]
# Default INSTALL_DIR: /workspace/chromium_libs

set -e

INSTALL_DIR="${1:-/workspace/chromium_libs}"
DEBS_DIR="${INSTALL_DIR}/.debs"

mkdir -p "$INSTALL_DIR" "$DEBS_DIR"

echo "Installing system libs for Chromium to: $INSTALL_DIR"

# Get the primary download URL for a debian bookworm amd64 package
get_deb_url() {
    curl -fsSL "https://packages.debian.org/bookworm/amd64/${1}/download" 2>/dev/null \
        | grep -o 'http[^"]*_amd64.deb' | head -1
}

# Download and extract a deb package into INSTALL_DIR
install_pkg() {
    local pkg="$1"
    local url
    url=$(get_deb_url "$pkg")
    if [ -z "$url" ]; then
        echo "  WARNING: no URL found for $pkg"
        return 0
    fi

    local deb="${DEBS_DIR}/${pkg}.deb"
    if [ ! -f "$deb" ]; then
        echo "  Downloading: $pkg ..."
        curl -fsSL "$url" -o "$deb"
    else
        echo "  Already downloaded: $pkg"
    fi

    local tmpdir
    tmpdir=$(mktemp -d "${DEBS_DIR}/tmp_XXXXXX")
    (
        cd "$tmpdir"
        ar x "$deb" 2>/dev/null
        if ls data.tar.* 1>/dev/null 2>&1; then
            tar -xf data.tar.* -C "$INSTALL_DIR/"
        fi
    )
    rm -rf "$tmpdir"
    echo "  Installed: $pkg"
}

# Core packages needed by Chromium headless shell on Debian bookworm.
# Includes transitive deps discovered by iterating ldd output.
PACKAGES="
libglib2.0-0
libnss3
libnspr4
libdbus-1-3
libatk1.0-0
libatk-bridge2.0-0
libxcb1
libxkbcommon0
libx11-6
libxcomposite1
libxdamage1
libxext6
libxfixes3
libxrandr2
libgbm1
libpango-1.0-0
libcairo2
libasound2
libatspi2.0-0
libcups2
libdrm2
libpixman-1-0
libfontconfig1
libfreetype6
libpng16-16
libxrender1
libxcb-shm0
libxcb-render0
libuuid1
libffi8
libpcre2-8-0
libmount1
libselinux1
libblkid1
zlib1g
libxi6
libwayland-server0
libxau6
libxdmcp6
"

echo ""
echo "Fetching and installing packages..."
for pkg in $PACKAGES; do
    install_pkg "$pkg"
done

LD_PATHS="${INSTALL_DIR}/usr/lib/x86_64-linux-gnu:${INSTALL_DIR}/usr/lib:${INSTALL_DIR}/lib/x86_64-linux-gnu:${INSTALL_DIR}/lib"

echo ""
echo "Done! Add to LD_LIBRARY_PATH:"
echo "  export LD_LIBRARY_PATH=\"${LD_PATHS}\""
echo ""
echo "Or source the generated env file:"
echo "  source ${INSTALL_DIR}/chromium-env.sh"

# Write a sourceable env file
cat > "${INSTALL_DIR}/chromium-env.sh" << EOF
# Auto-generated by install-system-libs.sh
export LD_LIBRARY_PATH="${LD_PATHS}\${LD_LIBRARY_PATH:+:\$LD_LIBRARY_PATH}"
EOF
echo "Wrote ${INSTALL_DIR}/chromium-env.sh"
