#!/bin/bash
# web_browse_agent wrapper script for datacenter environments
# Sets up LD_LIBRARY_PATH for Chromium system libraries and delegates to the real binary
#
# This wrapper is generated by 'make install-datacenter' and lives alongside the binary.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# The chromium_libs directory is expected next to the binary, or at the path
# stored in WEB_AGENT_CHROMIUM_LIBS env var.
CHROMIUM_LIBS="${WEB_AGENT_CHROMIUM_LIBS:-${SCRIPT_DIR}/chromium_libs}"

if [ -d "$CHROMIUM_LIBS" ]; then
    EXTRA_LD="${CHROMIUM_LIBS}/usr/lib/x86_64-linux-gnu:${CHROMIUM_LIBS}/usr/lib:${CHROMIUM_LIBS}/lib/x86_64-linux-gnu:${CHROMIUM_LIBS}/lib"
    export LD_LIBRARY_PATH="${EXTRA_LD}${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"
fi

# Execute the real binary
exec "${SCRIPT_DIR}/web_browse_agent.bin" "$@"
