#!/bin/bash
# Quick test script for colon command autocomplete

echo "=== Testing Colon Command Autocomplete ==="
echo ""
echo "This script will help you manually test the autocomplete feature."
echo ""
echo "Build successful. Now test manually:"
echo ""
echo "1. Run: ./build/klawed"
echo "2. Press ':' to enter command mode"
echo "3. Test these scenarios:"
echo ""
echo "   a) Type 'q' and press Tab"
echo "      → Should complete to 'quit'"
echo ""
echo "   b) Type 'n' and press Tab"  
echo "      → Should complete to 'no' (common prefix)"
echo "      → Press Tab again to see: 'Available: noh, nohlsearch'"
echo ""
echo "   c) Type 'w' and press Tab"
echo "      → Should show: 'Available: w, write, wq'"
echo ""
echo "   d) Type 'qu' and press Tab"
echo "      → Should complete to 'quit'"
echo ""
echo "   e) Type 'xyz' and press Tab"
echo "      → Should beep (no matches)"
echo ""
echo "   f) Just ':' and press Tab"
echo "      → Should beep (empty prefix)"
echo ""
echo "4. Test execution:"
echo "   - Type ':noh' (with Tab to complete), press Enter"
echo "     → Should clear search highlights and return to Normal mode"
echo ""
echo "5. Exit with ':q' + Tab + Enter"
echo ""
echo "Ready to test? Press Enter to launch klawed..."
read

./build/klawed
