# JS version file for development (no cache busting)
js.generated=2026-01-08T07:16:22.897Z
js.authUtils=authUtils.js
js.darkMode=darkMode.js
js.fileChat=fileChat.js
js.fileExplorer=fileExplorer.js
js.tabManager=tabManager.js
