package com.filesurf.service;

import com.filesurf.db.BlogDatabaseManager;
import com.filesurf.model.BlogCategory;
import com.filesurf.model.BlogPost;
import com.filesurf.model.BlogTag;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import org.eclipse.microprofile.config.inject.ConfigProperty;

import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.logging.Logger;

/**
 * Service for generating sitemap.xml and robots.txt for SEO purposes.
 */
@ApplicationScoped
public class SitemapService {

    private static final Logger LOGGER = Logger.getLogger(SitemapService.class.getName());

    @Inject
    BlogDatabaseManager db;

    @ConfigProperty(name = "blog.site.url", defaultValue = "https://filesurf.example.com")
    String siteUrl;

    @ConfigProperty(name = "blog.sitemap.max-urls", defaultValue = "1000")
    int maxUrls;

    private static final DateTimeFormatter ISO_DATE_FORMAT = 
        DateTimeFormatter.ofPattern("yyyy-MM-dd");

    private static final String SITEMAP_HEADER = 
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
        "<urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\">\n";

    private static final String SITEMAP_FOOTER = "</urlset>";

    /**
     * Generate XML sitemap with all published posts, categories, and tags.
     * 
     * @return XML sitemap content
     */
    public String generateSitemap() {
        StringBuilder sb = new StringBuilder();
        sb.append(SITEMAP_HEADER);

        try {
            // Add blog home page
            sb.append(createUrlEntry(siteUrl + "/blog", null, "daily", "1.0"));

            // Fetch all content
            int totalPosts = db.countPublishedPosts();
            int limit = Math.min(maxUrls - 1, totalPosts); // Reserve space for home page
            
            List<BlogPost> posts = db.getPublishedPosts(limit, 0);
            List<BlogCategory> categories = db.listCategories();
            List<BlogTag> tags = db.listTags();

            // Add posts (priority 0.8, weekly changefreq)
            for (BlogPost post : posts) {
                String lastmod = null;
                if (post.getUpdatedAt() != null) {
                    lastmod = post.getUpdatedAt().format(ISO_DATE_FORMAT);
                } else if (post.getPublishedAt() != null) {
                    lastmod = post.getPublishedAt().format(ISO_DATE_FORMAT);
                }
                sb.append(createUrlEntry(
                    siteUrl + "/blog/" + post.getSlug(),
                    lastmod,
                    "weekly",
                    "0.8"
                ));
            }

            // Add categories (priority 0.5, monthly changefreq)
            for (BlogCategory category : categories) {
                sb.append(createUrlEntry(
                    siteUrl + "/blog/category/" + category.getSlug(),
                    category.getCreatedAt() != null ? category.getCreatedAt().format(ISO_DATE_FORMAT) : null,
                    "monthly",
                    "0.5"
                ));
            }

            // Add tags (priority 0.5, monthly changefreq)
            for (BlogTag tag : tags) {
                sb.append(createUrlEntry(
                    siteUrl + "/blog/tag/" + tag.getSlug(),
                    tag.getCreatedAt() != null ? tag.getCreatedAt().format(ISO_DATE_FORMAT) : null,
                    "monthly",
                    "0.5"
                ));
            }

        } catch (Exception e) {
            LOGGER.severe("Error generating sitemap: " + e.getMessage());
        }

        sb.append(SITEMAP_FOOTER);
        
        LOGGER.info("Generated sitemap with up to " + maxUrls + " URLs");
        return sb.toString();
    }

    /**
     * Generate robots.txt content with sitemap reference.
     * 
     * @return robots.txt content
     */
    public String generateRobotsTxt() {
        StringBuilder sb = new StringBuilder();
        
        sb.append("# Robots.txt for ").append(siteUrl).append("\n");
        sb.append("# Generated by FileSurf Blog\n");
        sb.append("\n");
        
        // Default rules - allow all crawlers
        sb.append("User-agent: *\n");
        sb.append("Allow: /\n");
        sb.append("\n");
        
        // Sitemap location
        sb.append("Sitemap: ").append(siteUrl).append("/blog/sitemap.xml\n");
        
        // Also reference RSS/Atom feeds for discovery
        sb.append("Sitemap: ").append(siteUrl).append("/blog/rss.xml\n");
        sb.append("Sitemap: ").append(siteUrl).append("/blog/atom.xml\n");
        
        LOGGER.info("Generated robots.txt");
        return sb.toString();
    }

    /**
     * Create a single URL entry for the sitemap.
     * 
     * @param loc URL location
     * @param lastmod Last modification date (ISO format, can be null)
     * @param changefreq Change frequency (daily, weekly, monthly, etc.)
     * @param priority URL priority (0.0 to 1.0)
     * @return XML URL entry
     */
    private String createUrlEntry(String loc, String lastmod, String changefreq, String priority) {
        StringBuilder entry = new StringBuilder();
        entry.append("  <url>\n");
        entry.append("    <loc>").append(escapeXml(loc)).append("</loc>\n");
        
        if (lastmod != null) {
            entry.append("    <lastmod>").append(lastmod).append("</lastmod>\n");
        }
        
        entry.append("    <changefreq>").append(changefreq).append("</changefreq>\n");
        entry.append("    <priority>").append(priority).append("</priority>\n");
        entry.append("  </url>\n");
        
        return entry.toString();
    }

    /**
     * Escape special XML characters for safe inclusion in XML content.
     * 
     * @param str Input string (typically a URL)
     * @return Escaped string safe for XML
     */
    private String escapeXml(String str) {
        if (str == null) return "";
        return str.replace("&", "&amp;")
                  .replace("<", "&lt;")
                  .replace(">", "&gt;")
                  .replace("\"", "&quot;")
                  .replace("'", "&apos;");
    }
}
