#!/bin/bash
# Script to set up Stripe secrets for FileSurf v2
# Usage:
#   Local:  ./scripts/setup-stripe-secrets.sh
#   Remote: ./scripts/setup-stripe-secrets.sh --remote

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
REMOTE_MODE=false

# Parse arguments
if [ "$1" = "--remote" ] || [ "$1" = "-r" ]; then
    REMOTE_MODE=true
    REMOTE_HOST="filesurf-0"
    REMOTE_PATH="/root/filesurf_v2"
    echo "Remote mode: Will configure Stripe secrets on $REMOTE_HOST"
    echo ""
fi

echo "================================================"
echo "FileSurf v2 Stripe Secrets Setup"
echo "================================================"
echo ""

# Detect environment and set paths
if [ "$REMOTE_MODE" = true ]; then
    ENV_FILE="/etc/filesurf/.env"
    echo "Environment: Production (remote)"
    echo "Environment file: $ENV_FILE"
else
    # Check for existing environment file
    if [ -f "/etc/filesurf/.env" ]; then
        ENV_FILE="/etc/filesurf/.env"
        echo "Environment: Production (detected /etc/filesurf/.env)"
    elif [ -f "$PROJECT_ROOT/.env.local" ]; then
        ENV_FILE="$PROJECT_ROOT/.env.local"
        echo "Environment: Development (using .env.local)"
    else
        ENV_FILE="$PROJECT_ROOT/.env.local"
        echo "Environment: Development (will create .env.local)"
    fi
    echo "Environment file: $ENV_FILE"
fi

echo ""
echo "Step 1: Stripe API Keys"
echo "================================================"
echo "Get your API keys from: https://dashboard.stripe.com/apikeys"
echo ""

# Check if we should skip prompting (for automated setups)
if [ -n "$STRIPE_SECRET_KEY" ]; then
    echo "   Using STRIPE_SECRET_KEY from environment"
    SECRET_KEY="$STRIPE_SECRET_KEY"
else
    read -p "Enter Stripe Secret Key (sk_test_... or sk_live_...): " SECRET_KEY
fi

if [ -n "$STRIPE_PUBLIC_KEY" ]; then
    echo "   Using STRIPE_PUBLIC_KEY from environment"
    PUBLIC_KEY="$STRIPE_PUBLIC_KEY"
else
    read -p "Enter Stripe Public Key (pk_test_... or pk_live_...): " PUBLIC_KEY
fi

echo ""
echo "Step 2: Stripe Webhook"
echo "================================================"
echo "Configure webhook at: https://dashboard.stripe.com/webhooks"
echo "Endpoint URL: https://filesurf.io/api/stripe/webhook"
echo "Events to listen for:"
echo "  - checkout.session.completed"
echo "  - customer.subscription.created"
echo "  - customer.subscription.updated"
echo "  - customer.subscription.deleted"
echo "  - invoice.payment_succeeded"
echo "  - invoice.payment_failed"
echo ""

if [ -n "$STRIPE_WEBHOOK_SECRET" ]; then
    echo "   Using STRIPE_WEBHOOK_SECRET from environment"
    WEBHOOK_SECRET="$STRIPE_WEBHOOK_SECRET"
else
    read -p "Enter Stripe Webhook Secret (whsec_...): " WEBHOOK_SECRET
fi

echo ""
echo "Step 3: Stripe Price IDs"
echo "================================================"
echo "Create products and prices at: https://dashboard.stripe.com/products"
echo ""

if [ -n "$STRIPE_PRICE_BASIC" ]; then
    echo "   Using STRIPE_PRICE_BASIC from environment"
    PRICE_BASIC="$STRIPE_PRICE_BASIC"
else
    read -p "Enter Basic Plan Price ID (price_...): " PRICE_BASIC
fi

if [ -n "$STRIPE_PRICE_PRO" ]; then
    echo "   Using STRIPE_PRICE_PRO from environment"
    PRICE_PRO="$STRIPE_PRICE_PRO"
else
    read -p "Enter Professional Plan Price ID (price_...): " PRICE_PRO
fi

echo ""
echo "Step 4: Writing configuration..."
echo "================================================"

# Ensure directory exists
if [ "$REMOTE_MODE" = true ]; then
    ssh "$REMOTE_HOST" "mkdir -p /etc/filesurf"
else
    mkdir -p "$(dirname "$ENV_FILE")"
fi

# Create or update environment file
CONFIG_CONTENT="# Stripe Configuration
# Generated by setup-stripe-secrets.sh on $(date '+%Y-%m-%d %H:%M:%S')
# WARNING: Keep this file secure! It contains sensitive API keys.

STRIPE_SECRET_KEY=$SECRET_KEY
STRIPE_PUBLIC_KEY=$PUBLIC_KEY
STRIPE_WEBHOOK_SECRET=$WEBHOOK_SECRET

# Stripe Price IDs
STRIPE_PRICE_BASIC=$PRICE_BASIC
STRIPE_PRICE_PRO=$PRICE_PRO

# Application base URL
APP_BASE_URL=https://filesurf.io
"

if [ "$REMOTE_MODE" = true ]; then
    # Write to remote server
    echo "$CONFIG_CONTENT" | ssh "$REMOTE_HOST" "cat > $ENV_FILE && chmod 600 $ENV_FILE"
    echo "Configuration written to: $REMOTE_HOST:$ENV_FILE"
else
    # Write locally
    echo "$CONFIG_CONTENT" > "$ENV_FILE"
    chmod 600 "$ENV_FILE"
    echo "Configuration written to: $ENV_FILE"
fi

echo ""
echo "Step 5: Verifying configuration..."
echo "================================================"

# Verify the file was written correctly
if [ "$REMOTE_MODE" = true ]; then
    VERIFY_OUTPUT=$(ssh "$REMOTE_HOST" "cat $ENV_FILE")
else
    VERIFY_OUTPUT=$(cat "$ENV_FILE")
fi

# Check that all variables are present (masked values)
if echo "$VERIFY_OUTPUT" | grep -q "STRIPE_SECRET_KEY=" && \
   echo "$VERIFY_OUTPUT" | grep -q "STRIPE_PUBLIC_KEY=" && \
   echo "$VERIFY_OUTPUT" | grep -q "STRIPE_WEBHOOK_SECRET=" && \
   echo "$VERIFY_OUTPUT" | grep -q "STRIPE_PRICE_BASIC=" && \
   echo "$VERIFY_OUTPUT" | grep -q "STRIPE_PRICE_PRO="; then
    echo "   ✓ All Stripe secrets configured successfully"
else
    echo "   ✗ ERROR: Some configuration is missing!"
    exit 1
fi

echo ""
echo "================================================"
echo "Setup Complete!"
echo "================================================"
echo ""
echo "Next steps:"
if [ "$REMOTE_MODE" = true ]; then
    echo "1. Restart the service to apply changes:"
    echo "   ssh $REMOTE_HOST 'systemctl restart filesurf-v2'"
    echo ""
    echo "2. Check service status:"
    echo "   ssh $REMOTE_HOST 'systemctl status filesurf-v2'"
    echo ""
    echo "3. View logs:"
    echo "   ssh $REMOTE_HOST 'journalctl -u filesurf-v2 -f'"
else
    echo "1. Restart the application if running"
    echo "2. Test Stripe integration at http://localhost:9090/"
    echo ""
    echo "For production deployment:"
    echo "1. Run this script with --remote flag on the remote server"
    echo "2. Or manually configure /etc/filesurf/.env on the server"
fi
echo ""
echo "Stripe Dashboard: https://dashboard.stripe.com"
echo "Test cards: https://stripe.com/docs/testing#cards"
echo ""
